name: Code check

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  code_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check lint
        run: npm run lint

      - name: Check types
        run: npm run check-types

      - name: Vue TSC
        run: npm run vue-tsc
